import express from 'express'; import request from 'supertest'; import { beforeEach, describe, expect, it, vi } from 'vitest';
const db = vi.hoisted(() => ({ accountMember: { findFirst: vi.fn() }, listingCollection: { findFirst: vi.fn(), update: vi.fn() }, property: { count: vi.fn(), findMany: vi.fn() } }));
vi.mock('db', () => ({ prisma: db, Prisma: {} }));
vi.mock('@realestategear/portal-config', () => ({ classifierExpressionSchema: { parse: (v: unknown) => v }, collectionPredicateSchema: { parse: (v: unknown) => v }, getPortalConfig: () => ({ listings: { boardIds: [] }, compliance: { idxApproved: true }, classification: { initialAreas: [], definitions: [], providerAttributeMappings: {} } }) }));
vi.mock('search/collectionPredicate', () => ({ compileCollectionPredicate: () => ({ eligible: true }) }));
const router = (await import('../../../routes/ownerCollections.js')).default;
function app() { const value = express(); value.use(express.json()); value.use((req, _res, next) => { req.user = { id: 'owner-1' } as never; next(); }); value.use(router); value.use((error, _req, res, _next) => res.status(500).json({ error: String(error) })); return value; }
describe('owner collection scope', () => {
  beforeEach(() => { vi.clearAllMocks(); db.accountMember.findFirst.mockResolvedValue({ accountId: 'account-1' }); });
  it('fails closed for a cross-account collection id', async () => { db.listingCollection.findFirst.mockResolvedValue(null); const response = await request(app()).get('/collections/other'); expect(response.status).toBe(404); expect(db.listingCollection.findFirst).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'other', portal: { accountId: 'account-1' } } })); });
  it('publishes an owned collection', async () => { db.listingCollection.findFirst.mockResolvedValue({ id: 'c1', predicate: {}, portal: { id: 'p1', accountId: 'account-1', slug: 'portal' } }); db.listingCollection.update.mockResolvedValue({ id: 'c1', isPublished: true }); const response = await request(app()).patch('/collections/c1').send({ isPublished: true }); expect(response.status).toBe(200); expect(db.listingCollection.update).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'c1' }, data: { isPublished: true } })); });
  it('previews count and examples through the Postgres compiler', async () => { db.listingCollection.findFirst.mockResolvedValue({ id: 'c1', predicate: {}, portal: { id: 'p1', accountId: 'account-1', slug: 'portal', isActive: true, suspendedAt: null } }); db.property.count.mockResolvedValue(2); db.property.findMany.mockResolvedValue([{ id: 'home-1', address: '1 Main', city: 'Charlotte', state: 'NC' }]); const response = await request(app()).post('/collections/c1/preview').send({}); expect(response.body.count).toBe(2); expect(response.body.examples[0].whyMatched).toMatch(/authoritative/); });
});
