"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@realestategear/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@realestategear/ui/card";
import { Empty } from "@realestategear/ui/empty";
import { Input } from "@realestategear/ui/input";
import { NativeSelect } from "@realestategear/ui/native-select";
import { Skeleton } from "@realestategear/ui/skeleton";
import type { AgentDiscoveryResponse, AgentListingCard, AgentListingDetailResponse, AgentProperty, AgentPropertyListResponse } from "@/lib/agent";

async function request(path: string) {
  const response = await fetch(path, { cache: "no-store" });
  const body = await response.json().catch(() => ({}));
  if (response.status === 401) throw new Error("UNAUTHORIZED");
  if (!response.ok) throw new Error(body.error || "Search failed.");
  return body;
}
const money = (value?: number | null) => value == null ? "—" : new Intl.NumberFormat(undefined, { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString() : "—";
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="flex flex-col gap-3"><p className="text-sm text-destructive">{message}</p><Button variant="outline" onClick={retry}>Retry</Button></div>; }

function Filters({ mode }: { mode: "properties" | "listings" }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const update = (key: string, value: string) => { const next = new URLSearchParams(params.toString()); value ? next.set(key, value) : next.delete(key); next.delete("page"); router.replace(`${pathname}?${next}`); };
  return <form className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-4" aria-label={`${mode} search filters`} onSubmit={(e) => e.preventDefault()}>
    <label className="text-sm font-medium sm:col-span-2">Address or MLS ID<Input value={params.get("search") ?? params.get("q") ?? ""} onChange={(e) => update(mode === "listings" ? "q" : "search", e.target.value)} /></label>
    <label className="text-sm font-medium">City<Input value={params.get("city") ?? ""} onChange={(e) => update("city", e.target.value)} /></label>
    <label className="text-sm font-medium">Sort<NativeSelect value={params.get("sortBy") ?? "created_desc"} onChange={(e) => update("sortBy", e.target.value)}><option value="created_desc">Newest</option><option value="price_asc">Lowest price</option><option value="price_desc">Highest price</option></NativeSelect></label>
  </form>;
}

function PropertyCard({ property }: { property: AgentProperty }) { return <Link href={property.listingId ? `/agent/listings/${property.listingId}` : `/agent/properties?search=${encodeURIComponent(property.address)}`} className="flex gap-4 rounded-md border bg-card p-3 hover:bg-accent/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="h-24 w-32 shrink-0 overflow-hidden rounded border bg-muted">{property.imageUrl ? <img src={property.imageUrl} alt="" className="h-full w-full object-cover" /> : null}</div><div><p className="font-medium">{property.address}</p><p className="text-sm text-muted-foreground">{property.city}, {property.state} · {property.status || "Property"}</p><p className="mt-2 text-sm">{money(property.price ?? property.listPrice)} · {property.bedrooms ?? "—"} bd · {property.bathrooms ?? "—"} ba · {property.squareFeet ?? "—"} sqft</p>{property.mlsId ? <p className="text-xs text-muted-foreground">MLS {property.mlsId}</p> : null}</div></Link>; }
function ListingCard({ listing }: { listing: AgentListingCard }) { return <Link href={`/agent/listings/${listing.id}`} className="rounded-md border bg-card p-3 hover:bg-accent/30 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="mb-3 h-36 overflow-hidden rounded border bg-muted">{listing.imageUrl ? <img src={listing.imageUrl} alt="" className="h-full w-full object-cover" /> : null}</div><p className="font-medium">{listing.address}</p><p className="text-sm text-muted-foreground">{listing.city}, {listing.state}</p><p className="mt-2 font-semibold">{money(listing.price)}</p><p className="text-xs text-muted-foreground">{listing.status} · MLS {listing.mlsId || "—"}</p></Link>; }

export function AgentPropertiesPage() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [data, setData] = useState<AgentPropertyListResponse | null>(null); const [error, setError] = useState("");
  const query = params.toString(); const load = useCallback(async () => { try { setError(""); setData(await request(`/api/agent/properties${query ? `?${query}` : ""}`)); } catch (e) { if (e instanceof Error && e.message === "UNAUTHORIZED") router.push(`/agent/login?from=${encodeURIComponent(pathname)}`); else setError(e instanceof Error ? e.message : "Unable to load properties."); } }, [pathname, query, router]); useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data) return <Skeleton aria-label="Loading properties" className="h-96 w-full" />;
  return <div className="flex flex-col gap-6"><div><h1 className="text-xl font-semibold">Property catalog</h1><p className="mt-1 text-sm text-muted-foreground">{data.pagination.total} properties</p></div><Filters mode="properties" />{data.properties.length ? <div className="grid gap-3 md:grid-cols-2">{data.properties.map((property) => <PropertyCard key={property.id} property={property} />)}</div> : <Empty title="No properties found" description="Try a different address, city, or filter." />}{data.pagination.totalPages > 1 ? <Pagination page={data.pagination.page} totalPages={data.pagination.totalPages} /> : null}</div>;
}
function Pagination({ page, totalPages }: { page: number; totalPages: number }) { const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const go = (value: number) => { const next = new URLSearchParams(params.toString()); next.set("page", String(value)); router.replace(`${pathname}?${next}`); }; return <nav aria-label="Search pagination" className="flex justify-between"><Button variant="outline" disabled={page <= 1} onClick={() => go(page - 1)}>Previous</Button><span className="py-2 text-sm text-muted-foreground">Page {page} of {totalPages}</span><Button variant="outline" disabled={page >= totalPages} onClick={() => go(page + 1)}>Next</Button></nav>; }

export function AgentListingsPage() {
  const [data, setData] = useState<AgentDiscoveryResponse | null>(null); const [results, setResults] = useState<AgentListingCard[] | null>(null); const [error, setError] = useState(""); const params = useSearchParams(); const query = params.get("q")?.trim() ?? "";
  const load = useCallback(async () => { try { setError(""); if (query) setResults((await request(`/api/agent/listings/search?q=${encodeURIComponent(query)}`)).listings); else setData(await request("/api/agent/listings/discovery")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load listings."); } }, [query]); useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data && !results) return <Skeleton aria-label="Loading listings" className="h-96 w-full" />;
  const listings = results ?? data?.defaultFeed?.listings ?? []; return <div className="flex flex-col gap-6"><div><h1 className="text-xl font-semibold">Listing discovery</h1><p className="mt-1 text-sm text-muted-foreground">{data?.defaultFeed?.label || (query ? `Search results for ${query}` : "MLS listings")}</p></div><Filters mode="listings" />{data && !data.setup.hasMlsAccess ? <Empty title="MLS access is not connected" description="Connect a verified MLS board to discover listings." /> : listings.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{listings.map((listing) => <ListingCard key={listing.id} listing={listing} />)}</div> : <Empty title="No listings found" description="Try another address or MLS ID." />}{data?.segmentFeeds.map((feed) => feed.listings.length ? <section key={feed.segmentId}><h2 className="mb-3 font-semibold">{feed.segmentName}</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{feed.listings.map((listing) => <ListingCard key={listing.id} listing={listing} />)}</div></section> : null)}</div>;
}

export function AgentListingDetailPage({ id }: { id: string }) { const [data, setData] = useState<AgentListingDetailResponse | null>(null); const [error, setError] = useState(""); const load = useCallback(async () => { try { setData(await request(`/api/agent/listings/${id}`)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load listing."); } }, [id]); useEffect(() => { void load(); }, [load]); if (error) return <ErrorState message={error} retry={() => void load()} />; if (!data) return <Skeleton aria-label="Loading listing" className="h-96 w-full" />; return <div className="flex flex-col gap-6"><div><Link href="/agent/listings" className="text-sm text-primary hover:underline">Back to discovery</Link><h1 className="mt-3 text-2xl font-semibold">{data.listing.address}</h1><p className="text-muted-foreground">{data.listing.city}, {data.listing.state} · MLS {data.listing.mlsId}</p></div><div className="grid gap-6 lg:grid-cols-3"><Card className="lg:col-span-2"><CardContent className="grid gap-3 pt-6 sm:grid-cols-2">{data.media.map((media) => <img key={media.id} src={media.url} alt={media.caption || `Listing image ${media.order}`} className="max-h-80 w-full rounded border object-cover" />)}</CardContent></Card><Card><CardHeader><CardTitle>{money(data.listing.price)}</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>Status: {data.listing.status}</p><p>Listed: {date(data.listing.listDate)}</p><p>Type: {data.property.propertyType || "—"}</p><p>Facts: {data.property.bedrooms ?? "—"} bd · {data.property.bathrooms ?? "—"} ba · {data.property.squareFeet ?? "—"} sqft</p><p>Year built: {data.property.yearBuilt ?? "—"}</p><p>Brokerage: {data.listing.brokerage.name || "—"}</p></CardContent></Card></div><Card><CardHeader><CardTitle>Listing history</CardTitle></CardHeader><CardContent>{data.propertyHistory.length ? <ul className="divide-y">{data.propertyHistory.map((item) => <li key={item.id} className="flex justify-between py-3 text-sm"><span>{item.status} · {item.mlsId}</span><span>{money(item.price)}</span></li>)}</ul> : <Empty compact title="No listing history" description="No prior listing records were returned." />}</CardContent></Card><Card><CardHeader><CardTitle>Transaction workflow</CardTitle></CardHeader><CardContent>{data.workflow.transactions.length ? <ul className="divide-y">{data.workflow.transactions.map((tx) => <li key={tx.id} className="flex justify-between py-3 text-sm"><Link className="text-primary hover:underline" href={`/agent/transactions/${tx.id}`}>{tx.address || "Transaction"}</Link><span>{tx.stage}</span></li>)}</ul> : <p className="text-sm text-muted-foreground">{data.workflow.canCreateTransaction ? "No transaction is linked to this property." : "Transaction workflow unavailable."}</p>}</CardContent></Card></div>; }

export function AgentSearchPalette() { const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [data, setData] = useState<Record<string, { items: Array<Record<string, unknown>>; total: number }> | null>(null); const [suggestions, setSuggestions] = useState<Array<Record<string, unknown>>>([]); useEffect(() => { const onKey = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setOpen(true); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []); useEffect(() => { if (!open || query.trim().length < 2) { setSuggestions([]); return; } const timer = window.setTimeout(() => { void fetch(`/api/search/suggestions?q=${encodeURIComponent(query)}`).then((r) => r.json()).then((body) => setSuggestions(body.suggestions ?? [])); }, 200); return () => window.clearTimeout(timer); }, [open, query]); useEffect(() => { if (!open || !query.trim()) { setData(null); return; } const timer = window.setTimeout(() => { void fetch(`/api/agent/search?q=${encodeURIComponent(query)}&limit=5`).then((r) => r.json()).then(setData); }, 250); return () => window.clearTimeout(timer); }, [open, query]); return <>{<Button variant="outline" aria-label="Open global search" onClick={() => setOpen(true)}>Search <span className="ml-2 text-xs text-muted-foreground">Ctrl K</span></Button>}{open ? <div role="dialog" aria-modal="true" aria-label="Global search" className="fixed inset-0 z-50 bg-background/80 p-4 backdrop-blur-sm" onClick={() => setOpen(false)}><Card className="mx-auto mt-16 max-w-2xl" onClick={(e) => e.stopPropagation()}><CardContent className="pt-6"><Input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search contacts, transactions, properties, tasks" />{suggestions.length ? <ul className="mt-3 border-b pb-3 text-sm">{suggestions.map((item, index) => <li key={`${String(item.value)}-${index}`} className="py-1">{String(item.display || item.value)}</li>)}</ul> : null}{data ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(data).map(([type, group]) => <section key={type}><h2 className="text-xs font-semibold uppercase text-muted-foreground">{type} ({group.total})</h2>{group.items.map((item, index) => <p key={index} className="truncate py-1 text-sm">{String(item.address || item.title || item.name || item.firstName || "Result")}</p>)}</section>)}</div> : null}<Button className="mt-4" variant="outline" onClick={() => setOpen(false)}>Close</Button></CardContent></Card></div> : null}</>; }
