"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@realestategear/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@realestategear/ui/card";
import { Empty } from "@realestategear/ui/empty";
import { Input } from "@realestategear/ui/input";
import { Skeleton } from "@realestategear/ui/skeleton";

type GoogleStatus = { connected: boolean; provider: string; email?: string; displayName?: string; scopes?: string[]; availableScopes?: string[]; accessTokenExpiresAt?: string | null; lastSyncedAt?: string | null; driveScopeGranted?: boolean };
type GoogleEvent = { id: string; status: string; title: string; description?: string | null; location?: string | null; htmlLink?: string | null; isAllDay: boolean; start?: string | null; end?: string | null; attendees: Array<{ email?: string | null; displayName?: string | null; responseStatus?: string | null }> };
type Activity = { contact: { id: string; email?: string | null; name: string }; emails: Array<{ id: string; subject?: string | null; from?: string | null; snippet?: string | null; lastMessageAt?: string | null; unread?: boolean; messageCount?: number }>; events: GoogleEvent[] };

async function request(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (response.status === 401) throw new Error("UNAUTHORIZED");
  if (!response.ok) throw new Error(body.error || "Google Workspace request failed.");
  return body;
}
function errorMessage(error: unknown) { const text = error instanceof Error ? error.message : "Google Workspace request failed."; return /configure|client|token|unavailable|denied|expired/i.test(text) ? text : text; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="flex flex-col gap-3"><p className="text-sm text-destructive">{message === "UNAUTHORIZED" ? "You are not authorized to access Google Workspace." : message}</p><Button variant="outline" onClick={retry}>Retry</Button></div>; }
function date(value?: string | null) { return value ? new Date(value).toLocaleString() : "No date"; }

export function AgentGoogleWorkspacePage() {
  const [status, setStatus] = useState<GoogleStatus | null>(null); const [scopes, setScopes] = useState<string[]>([]); const [error, setError] = useState("");
  const [code, setCode] = useState(""); const [redirectUri, setRedirectUri] = useState(""); const [connecting, setConnecting] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setError(""); const [next, scopeData] = await Promise.all([request("/api/agent/google/status"), request("/api/agent/google/scopes")]); setStatus(next); setScopes(next.availableScopes ?? scopeData.scopes ?? []); } catch (cause) { setError(errorMessage(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  const connect = async (event: React.FormEvent) => { event.preventDefault(); try { setConnecting(true); setMessage(""); await request("/api/agent/google/oauth/callback", { method: "POST", body: JSON.stringify({ code, redirectUri }) }); setCode(""); setMessage("Google Workspace connected."); await load(); } catch (cause) { setMessage(errorMessage(cause)); } finally { setConnecting(false); } };
  const disconnect = async () => { if (!window.confirm("Disconnect Google Workspace?")) return; try { await request("/api/agent/google/connection", { method: "DELETE" }); setMessage("Google Workspace disconnected."); await load(); } catch (cause) { setMessage(errorMessage(cause)); } };
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!status) return <Skeleton aria-label="Loading Google Workspace" className="h-96 w-full" />;
  return <div className="flex flex-col gap-6"><div><h1 className="text-xl font-semibold">Google Workspace</h1><p className="mt-1 text-sm text-muted-foreground">Connect Google Calendar, Gmail activity, and Drive actions without exposing Google credentials in the browser.</p></div><Card><CardHeader><CardTitle>{status.connected ? "Connected" : "Disconnected"}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{status.connected ? <><p>{status.displayName || status.email || "Google account"}{status.email ? ` · ${status.email}` : ""}</p><p className="text-muted-foreground">Last synced: {date(status.lastSyncedAt)}</p>{status.accessTokenExpiresAt && new Date(status.accessTokenExpiresAt) <= new Date() ? <p className="text-amber-700">Connection expired or needs renewal. Reconnect below.</p> : null}<Button variant="destructive" onClick={() => void disconnect()}>Disconnect Google</Button></> : <p className="text-muted-foreground">No Google account is connected.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Required scopes</CardTitle><p className="text-xs text-muted-foreground">Google grants are shown as names only; client secrets and encrypted token values never reach this page.</p></CardHeader><CardContent>{scopes.length ? <ul className="list-disc space-y-1 pl-5 text-sm">{scopes.map((scope) => <li key={scope}>{scope}</li>)}</ul> : <Empty compact title="Scopes unavailable" description="Google integration is not configured on this server." />}</CardContent></Card><Card><CardHeader><CardTitle>OAuth connection</CardTitle><p className="text-sm text-muted-foreground">Complete the Google consent flow using your configured OAuth client, then submit the authorization code and matching redirect URI here.</p></CardHeader><CardContent><form className="space-y-3" onSubmit={connect}><label className="text-sm font-medium">Authorization code<Input aria-label="Google authorization code" value={code} onChange={(e) => setCode(e.target.value)} required /></label><label className="text-sm font-medium">Redirect URI<Input aria-label="Google redirect URI" value={redirectUri} onChange={(e) => setRedirectUri(e.target.value)} required placeholder="https://your-app.example.com/oauth/callback" /></label>{message ? <p role="status" className="text-sm text-muted-foreground">{message}</p> : null}<Button type="submit" disabled={connecting}>{connecting ? "Connecting..." : "Connect Google"}</Button></form></CardContent></Card><GoogleCalendar /></div>;
}

export function GoogleCalendar() {
  const [events, setEvents] = useState<GoogleEvent[] | null>(null); const [nextPageToken, setNextPageToken] = useState<string | null>(null); const [error, setError] = useState(""); const [loadingMore, setLoadingMore] = useState(false);
  const load = useCallback(async (pageToken?: string) => { try { setError(""); const data = await request(`/api/agent/google/calendar?limit=20${pageToken ? `&pageToken=${encodeURIComponent(pageToken)}` : ""}`); setEvents((current) => pageToken ? [...(current ?? []), ...(data.events ?? [])] : data.events ?? []); setNextPageToken(data.nextPageToken ?? null); } catch (cause) { setError(errorMessage(cause)); } finally { setLoadingMore(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <Card><CardHeader><CardTitle>Google Calendar</CardTitle><p className="text-xs text-muted-foreground">Upcoming events from the connected primary calendar.</p></CardHeader><CardContent>{error ? <ErrorState message={error} retry={() => void load()} /> : !events ? <Skeleton aria-label="Loading Google Calendar" className="h-40 w-full" /> : events.length ? <><ul className="divide-y">{events.map((event) => <li key={event.id} className="py-3"><p className="font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{date(event.start)} · {event.location || "No location"}</p>{event.htmlLink ? <a className="text-xs text-primary underline" href={event.htmlLink} target="_blank" rel="noreferrer">Open in Google Calendar</a> : null}</li>)}</ul>{nextPageToken ? <Button className="mt-3" variant="outline" disabled={loadingMore} onClick={() => { setLoadingMore(true); void load(nextPageToken); }}>{loadingMore ? "Loading..." : "Load more"}</Button> : null}</> : <Empty compact title="No upcoming events" description="Your connected Google Calendar has no upcoming events." />}</CardContent></Card>;
}

export function GoogleContactActivity({ contactId }: { contactId: string }) {
  const [activity, setActivity] = useState<Activity | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); setActivity(await request(`/api/agent/google/contacts/${contactId}/activity`)); } catch (cause) { setError(errorMessage(cause)); } }, [contactId]);
  useEffect(() => { void load(); }, [load]);
  if (error) return <Card><CardContent className="pt-5"><ErrorState message={error} retry={() => void load()} /></CardContent></Card>;
  if (!activity) return <Card><CardContent className="pt-5"><Skeleton aria-label="Loading Google activity" className="h-32 w-full" /></CardContent></Card>;
  return <Card><CardHeader><CardTitle>Google activity</CardTitle><p className="text-xs text-muted-foreground">Gmail and calendar activity found for {activity.contact.name}. No message content is sent or modified here.</p></CardHeader><CardContent className="space-y-4">{activity.emails.length ? <section><h3 className="text-sm font-medium">Email threads</h3><ul className="divide-y">{activity.emails.map((email) => <li key={email.id} className="py-2 text-sm"><p>{email.subject || "(No subject)"}</p><p className="text-xs text-muted-foreground">{email.from || "Unknown sender"} · {date(email.lastMessageAt)}</p></li>)}</ul></section> : <Empty compact title="No email activity" description="No matching Gmail threads were found." />}{activity.events.length ? <section><h3 className="text-sm font-medium">Calendar events</h3><ul className="divide-y">{activity.events.map((event) => <li key={event.id} className="py-2 text-sm">{event.title}<span className="ml-2 text-xs text-muted-foreground">{date(event.start)}</span></li>)}</ul></section> : <Empty compact title="No calendar activity" description="No matching Google Calendar events were found." />}</CardContent></Card>;
}
