"use client";

import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@realestategear/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@realestategear/ui/card";
import { Empty } from "@realestategear/ui/empty";
import { Input } from "@realestategear/ui/input";
import { NativeSelect } from "@realestategear/ui/native-select";
import { Skeleton } from "@realestategear/ui/skeleton";
import { Textarea } from "@realestategear/ui/textarea";
import type { AgentContact, AgentEvent, AgentNote, AgentTask } from "@/lib/agent";

async function request(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (response.status === 401) throw new Error("UNAUTHORIZED");
  if (!response.ok) throw new Error(body.error || "Request failed.");
  return body;
}
const date = (value?: string | null) => value ? new Date(value).toLocaleString() : "No date";
const ErrorState = ({ message, retry }: { message: string; retry: () => void }) => <div role="alert" className="flex flex-col gap-3"><p className="text-sm text-destructive">{message}</p><Button variant="outline" onClick={retry}>Retry</Button></div>;

const TASK_DEFAULT = { title: "", description: "", dueDate: "", priority: "MEDIUM", status: "TODO", contactId: "", transactionId: "" };
function TaskForm({ initial = TASK_DEFAULT, onSubmit, submitLabel }: { initial?: typeof TASK_DEFAULT; onSubmit: (value: typeof TASK_DEFAULT) => Promise<void>; submitLabel: string }) {
  const [value, setValue] = useState(initial); const [error, setError] = useState("");
  const set = (key: keyof typeof TASK_DEFAULT, next: string) => setValue((current) => ({ ...current, [key]: next }));
  return <form aria-label="Task form" className="flex flex-col gap-3" onSubmit={async (event) => { event.preventDefault(); if (!value.title.trim()) { setError("Title is required."); return; } setError(""); await onSubmit(value); }}><p role="alert" className="text-sm text-destructive">{error}</p><label className="text-sm font-medium">Title<Input required value={value.title} onChange={(e) => set("title", e.target.value)} /></label><label className="text-sm font-medium">Description<Textarea value={value.description} onChange={(e) => set("description", e.target.value)} /></label><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-medium">Due date<Input type="datetime-local" value={value.dueDate} onChange={(e) => set("dueDate", e.target.value)} /></label><label className="text-sm font-medium">Priority<NativeSelect value={value.priority} onChange={(e) => set("priority", e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></NativeSelect></label><label className="text-sm font-medium">Status<NativeSelect value={value.status} onChange={(e) => set("status", e.target.value)}><option>TODO</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></NativeSelect></label></div><Button type="submit">{submitLabel}</Button></form>;
}

export function AgentTasksPage() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [data, setData] = useState<{ tasks: AgentTask[]; pagination: { page: number; totalPages: number; total: number } } | null>(null); const [error, setError] = useState(""); const [creating, setCreating] = useState(false); const query = params.toString();
  const load = useCallback(async () => { try { setError(""); setData(await request(`/api/agent/tasks${query ? `?${query}` : ""}`)); } catch (err) { if (err instanceof Error && err.message === "UNAUTHORIZED") router.push(`/agent/login?from=${encodeURIComponent(pathname)}`); else setError(err instanceof Error ? err.message : "Unable to load tasks."); } }, [pathname, query, router]); useEffect(() => { void load(); }, [load]);
  const update = (key: string, value: string) => { const next = new URLSearchParams(params.toString()); value ? next.set(key, value) : next.delete(key); if (key !== "page") next.delete("page"); router.replace(`${pathname}?${next}`); };
  if (error) return <ErrorState message={error} retry={() => void load()}/>; if (!data) return <Skeleton aria-label="Loading tasks" className="h-80 w-full"/>;
  return <div className="flex flex-col gap-6"><div className="flex items-end justify-between"><div><h1 className="text-xl font-semibold">Tasks</h1><p className="mt-1 text-sm text-muted-foreground">{data.pagination.total} tasks</p></div><Button onClick={() => setCreating((v) => !v)}>{creating ? "Close" : "Add task"}</Button></div>{creating ? <Card><CardHeader><CardTitle>Create task</CardTitle></CardHeader><CardContent><TaskForm submitLabel="Create task" onSubmit={async (value) => { await request("/api/agent/tasks", { method: "POST", body: JSON.stringify(value) }); setCreating(false); await load(); }}/></CardContent></Card> : null}<div className="grid gap-3 rounded-md border bg-card p-4 sm:grid-cols-3"><label className="text-sm font-medium">Search<Input value={params.get("search") ?? ""} onChange={(e) => update("search", e.target.value)}/></label><label className="text-sm font-medium">Status<NativeSelect value={params.get("status") ?? ""} onChange={(e) => update("status", e.target.value)}><option value="">All</option><option>TODO</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></NativeSelect></label><label className="text-sm font-medium">Priority<NativeSelect value={params.get("priority") ?? ""} onChange={(e) => update("priority", e.target.value)}><option value="">All</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>URGENT</option></NativeSelect></label></div>{data.tasks.length ? <ul className="divide-y rounded-md border bg-card">{data.tasks.map((task) => <TaskRow key={task.id} task={task} onChange={load}/>)}</ul> : <Empty title="No tasks found" description="Create a task or adjust your filters."/>}</div>;
}

function TaskRow({ task, onChange }: { task: AgentTask; onChange: () => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const save = async (value: typeof TASK_DEFAULT) => { await request(`/api/agent/tasks/${task.id}`, { method: "PUT", body: JSON.stringify(value) }); setEditing(false); await onChange(); };
  return <li className="px-4 py-4">{editing ? <TaskForm initial={{ title: task.title, description: task.description ?? "", dueDate: task.dueDate?.slice(0, 16) ?? "", priority: task.priority, status: task.status, contactId: task.contactId ?? "", transactionId: task.transactionId ?? "" }} submitLabel="Save task" onSubmit={save}/> : <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{task.title}</p><p className="text-xs text-muted-foreground">{task.status} · {task.priority} · {date(task.dueDate)}</p><p className="mt-1 text-xs">{task.contact ? <Link className="text-primary hover:underline" href={`/agent/contacts/${task.contact.id}`}>{task.contact.firstName} {task.contact.lastName}</Link> : null}{task.transaction ? <Link className="ml-3 text-primary hover:underline" href={`/agent/transactions/${task.transaction.id}`}>{task.transaction.address || "Transaction"}</Link> : null}</p></div><div className="flex gap-2"><Button size="xs" variant="ghost" onClick={() => setEditing(true)}>Edit</Button><Button size="xs" variant="ghost" onClick={async () => { if (window.confirm("Delete this task?")) { await request(`/api/agent/tasks/${task.id}`, { method: "DELETE" }); await onChange(); } }}>Delete</Button></div></div>}</li>;
}

const EVENT_TYPES = ["HOME_TOUR", "BUYER_CONSULTATION", "LISTING_CONSULTATION", "MEETING", "INSPECTION", "WALKTHROUGH", "CLOSING", "APPRAISAL", "OTHER"];
const EVENT_DEFAULT = { type: "MEETING", startAt: "", endAt: "", location: "", description: "", status: "SCHEDULED", transactionId: "", contactId: "" };
function EventForm({ initial = EVENT_DEFAULT, submitLabel, onSubmit }: { initial?: typeof EVENT_DEFAULT; submitLabel: string; onSubmit: (value: typeof EVENT_DEFAULT) => Promise<void> }) { const [value, setValue] = useState(initial); const set = (key: keyof typeof EVENT_DEFAULT, next: string) => setValue((current) => ({ ...current, [key]: next })); return <form aria-label="Event form" className="grid gap-3 sm:grid-cols-2" onSubmit={async (e) => { e.preventDefault(); await onSubmit(value); }}><label className="text-sm font-medium">Type<NativeSelect value={value.type} onChange={(e) => set("type", e.target.value)}>{EVENT_TYPES.map((type) => <option key={type}>{type}</option>)}</NativeSelect></label><label className="text-sm font-medium">Status<NativeSelect value={value.status} onChange={(e) => set("status", e.target.value)}><option>SCHEDULED</option><option>COMPLETED</option><option>CANCELLED</option></NativeSelect></label><label className="text-sm font-medium">Start<Input required type="datetime-local" value={value.startAt} onChange={(e) => set("startAt", e.target.value)}/></label><label className="text-sm font-medium">End<Input required type="datetime-local" value={value.endAt} onChange={(e) => set("endAt", e.target.value)}/></label><label className="text-sm font-medium sm:col-span-2">Location<Input value={value.location} onChange={(e) => set("location", e.target.value)}/></label><label className="text-sm font-medium sm:col-span-2">Description<Textarea value={value.description} onChange={(e) => set("description", e.target.value)}/></label><Button className="sm:col-span-2" type="submit">{submitLabel}</Button></form>; }

export function AgentEventsPage() {
  const [data, setData] = useState<{ events: AgentEvent[]; pagination: { total: number } } | null>(null); const [error, setError] = useState(""); const [creating, setCreating] = useState(false);
  const load = useCallback(async () => { try { setData(await request("/api/agent/events")); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load events."); } }, []); useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()}/>; if (!data) return <Skeleton aria-label="Loading events" className="h-80 w-full"/>;
  return <div className="flex flex-col gap-6"><div className="flex items-end justify-between"><div><h1 className="text-xl font-semibold">Calendar</h1><p className="mt-1 text-sm text-muted-foreground">Google Calendar integration will be expanded in a later task.</p></div><Button onClick={() => setCreating((v) => !v)}>{creating ? "Close" : "Add event"}</Button></div>{creating ? <Card><CardHeader><CardTitle>Create event</CardTitle></CardHeader><CardContent><EventForm submitLabel="Create event" onSubmit={async (value) => { await request("/api/agent/events", { method: "POST", body: JSON.stringify(value) }); setCreating(false); await load(); }}/></CardContent></Card> : null}{data.events.length ? <ul className="divide-y rounded-md border bg-card">{data.events.map((event) => <EventRow key={event.id} event={event} onChange={load}/>)}</ul> : <Empty title="No events scheduled" description="Create an event to start your calendar."/>}</div>;
}

function EventRow({ event, onChange }: { event: AgentEvent; onChange: () => Promise<void> }) { const [editing, setEditing] = useState(false); const [contactId, setContactId] = useState(""); const [role, setRole] = useState("ATTENDEE"); const save = async (value: typeof EVENT_DEFAULT) => { await request(`/api/agent/events/${event.id}`, { method: "PUT", body: JSON.stringify(value) }); setEditing(false); await onChange(); }; return <li className="px-4 py-4">{editing ? <EventForm initial={{ type: event.type, startAt: event.startAt.slice(0, 16), endAt: event.endAt.slice(0, 16), location: event.location ?? "", description: event.description ?? "", status: event.status, transactionId: event.transactionId ?? "", contactId: "" }} submitLabel="Save event" onSubmit={save}/> : <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{event.title}</p><p className="text-xs text-muted-foreground">{event.status} · {date(event.startAt)} · {event.location || "No location"}</p>{event.transaction ? <Link href={`/agent/transactions/${event.transaction.id}`} className="text-xs text-primary hover:underline">{event.transaction.address || "Transaction"}</Link> : null}<div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="font-medium">Attendees:</span>{event.attendees.length ? event.attendees.map((attendee) => <span key={attendee.id} className="rounded border px-2 py-1">{attendee.contact.firstName} {attendee.contact.lastName}<button type="button" className="ml-1 text-destructive underline" onClick={async () => { await request(`/api/agent/events/${event.id}/attendees/${attendee.id}`, { method: "DELETE" }); await onChange(); }}>Remove</button></span>) : <span>None</span>}</div><div className="mt-2 flex flex-wrap gap-2"><Input aria-label={`Contact ID for ${event.title}`} placeholder="Contact ID" value={contactId} onChange={(e) => setContactId(e.target.value)} /><Input aria-label={`Attendee role for ${event.title}`} placeholder="Role" value={role} onChange={(e) => setRole(e.target.value)} /><Button size="xs" variant="outline" disabled={!contactId.trim()} onClick={async () => { await request(`/api/agent/events/${event.id}/attendees`, { method: "POST", body: JSON.stringify({ contactId, role }) }); setContactId(""); await onChange(); }}>Add attendee</Button></div></div><div className="flex gap-2"><Button size="xs" variant="ghost" onClick={() => setEditing(true)}>Edit</Button>{event.status === "SCHEDULED" ? <Button size="xs" onClick={async () => { await request(`/api/agent/events/${event.id}/complete`, { method: "POST", body: JSON.stringify({}) }); await onChange(); }}>Complete</Button> : null}<Button size="xs" variant="ghost" onClick={async () => { if (window.confirm("Delete this event?")) { await request(`/api/agent/events/${event.id}`, { method: "DELETE" }); await onChange(); } }}>Delete</Button></div></div>}</li>; }

export function AgentNotesPage() { const [data, setData] = useState<{ notes: AgentNote[]; pagination: { total: number } } | null>(null); const [body, setBody] = useState(""); const [error, setError] = useState(""); const load = useCallback(async () => { try { setData(await request("/api/agent/notes")); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load notes."); } }, []); useEffect(() => { void load(); }, [load]); if (error) return <ErrorState message={error} retry={() => void load()}/>; if (!data) return <Skeleton aria-label="Loading notes" className="h-80 w-full"/>; return <div className="flex flex-col gap-6"><div><h1 className="text-xl font-semibold">Notes</h1><p className="mt-1 text-sm text-muted-foreground">{data.pagination.total} notes</p></div><Card><CardContent className="pt-6"><form className="flex flex-col gap-3" onSubmit={async (e) => { e.preventDefault(); if (!body.trim()) return; await request("/api/agent/notes", { method: "POST", body: JSON.stringify({ body }) }); setBody(""); await load(); }}><label className="text-sm font-medium">New note<Textarea value={body} onChange={(e) => setBody(e.target.value)} /></label><Button type="submit" disabled={!body.trim()}>Add note</Button></form></CardContent></Card>{data.notes.length ? <ul className="divide-y rounded-md border bg-card">{data.notes.map((note) => <li key={note.id} className="flex items-start justify-between gap-3 px-4 py-4"><div><p className="whitespace-pre-wrap text-sm">{note.body}</p><p className="mt-1 text-xs text-muted-foreground">{date(note.createdAt)}</p></div><Button size="xs" variant="ghost" onClick={async () => { if (window.confirm("Delete this note?")) { await request(`/api/agent/notes/${note.id}`, { method: "DELETE" }); await load(); } }}>Delete</Button></li>)}</ul> : <Empty title="No notes yet" description="Capture context for your workspace here."/>}</div>; }

export function AgentTaskPanel({ contactId, transactionId }: { contactId?: string; transactionId?: string }) { const [tasks, setTasks] = useState<AgentTask[]>([]); const load = useCallback(async () => { const query = new URLSearchParams({ ...(contactId ? { contactId } : {}), ...(transactionId ? { transactionId } : {}) }); const result = await request(`/api/agent/tasks?${query}`); setTasks(result.tasks); }, [contactId, transactionId]); useEffect(() => { void load(); }, [load]); return <Card><CardHeader><CardTitle>Related tasks</CardTitle></CardHeader><CardContent>{tasks.length ? <ul className="divide-y">{tasks.map((task) => <li key={task.id} className="py-2 text-sm">{task.title}<span className="ml-2 text-xs text-muted-foreground">{task.status}</span></li>)}</ul> : <Empty compact title="No related tasks" description="Tasks linked to this record will appear here."/>}</CardContent></Card>; }
export function AgentNotePanel({ contactId, transactionId }: { contactId?: string; transactionId?: string }) { const [notes, setNotes] = useState<AgentNote[]>([]); const [body, setBody] = useState(""); const load = useCallback(async () => { const query = new URLSearchParams({ ...(contactId ? { contactId } : {}), ...(transactionId ? { transactionId } : {}) }); const result = await request(`/api/agent/notes?${query}`); setNotes(result.notes); }, [contactId, transactionId]); useEffect(() => { void load(); }, [load]); return <Card><CardHeader><CardTitle>Related notes</CardTitle></CardHeader><CardContent><form className="flex gap-2" onSubmit={async (e) => { e.preventDefault(); if (!body.trim()) return; await request("/api/agent/notes", { method: "POST", body: JSON.stringify({ body, contactId, transactionId }) }); setBody(""); await load(); }}><Input aria-label="Related note" value={body} onChange={(e) => setBody(e.target.value)} placeholder="Add a note" /><Button disabled={!body.trim()}>Add</Button></form>{notes.length ? <ul className="mt-3 divide-y">{notes.map((note) => <li key={note.id} className="py-2 text-sm">{note.body}</li>)}</ul> : <Empty compact title="No related notes" description="Add context to this record."/>}</CardContent></Card>; }
