"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Button } from "@realestategear/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@realestategear/ui/card";
import { Empty } from "@realestategear/ui/empty";
import { Input } from "@realestategear/ui/input";
import { NativeSelect } from "@realestategear/ui/native-select";
import { Skeleton } from "@realestategear/ui/skeleton";

type Summary = { window: { from: string; to: string }; closings: number; volume: number; commission: number; missingDataCount: number; prev: { closings: number; volume: number; commission: number }; deltaPct: { closings: number; volume: number; commission: number } };
type Point = { bucket: string; closings: number; volume: number; commission: number };
type Forecast = { projectedClosings: number; projectedVolume: number; projectedCommission: number; byStage: Array<{ stage: string; probability: number; count: number; projectedClosings: number; projectedVolume: number; projectedCommission: number }> };
type Report = { id: string; title: string; subjectPropertyAddress: string; subjectPropertyData?: Record<string, unknown>; comparables?: Array<Record<string, unknown>>; aiAnalysis?: string | null; status?: string; createdAt?: string; updatedAt?: string };
type ReportsResponse = { reports: Report[]; pagination: { page: number; totalPages: number; total: number } };

async function request(path: string, init?: RequestInit) {
  const response = await fetch(path, { ...init, cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({}));
  if (response.status === 401) throw new Error("UNAUTHORIZED");
  if (!response.ok) throw new Error(body.error || "Report request failed.");
  return body;
}
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const delta = (value: number) => `${value >= 0 ? "+" : ""}${value.toFixed(1)}%`;

function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div role="alert" className="flex flex-col gap-3"><p className="text-sm text-destructive">{message === "UNAUTHORIZED" ? "You are not authorized to view reports." : message}</p><Button variant="outline" onClick={retry}>Retry</Button></div>; }
function Metric({ label, value, change }: { label: string; value: string | number; change?: number }) { return <Card><CardContent className="pt-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p>{change !== undefined ? <p className="mt-1 text-xs text-muted-foreground">{delta(change)} vs previous period</p> : null}</CardContent></Card>; }

export function AgentReportsPage() {
  const [summary, setSummary] = useState<Summary | null>(null); const [trend, setTrend] = useState<Point[]>([]); const [forecast, setForecast] = useState<Forecast | null>(null); const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); const query = "granularity=month"; const [nextSummary, nextTrend, nextForecast] = await Promise.all([request(`/api/agent/reports/summary?${query}`), request(`/api/agent/reports/trend?${query}`), request(`/api/agent/reports/forecast`)]); setSummary(nextSummary); setTrend(nextTrend.points ?? []); setForecast(nextForecast); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load reports."); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (error) return <ErrorState message={error} retry={() => void load()} />; if (!summary || !forecast) return <Skeleton aria-label="Loading reports" className="h-96 w-full" />;
  const max = Math.max(...trend.map((point) => point.closings), 1);
  return <div className="flex flex-col gap-6"><div><h1 className="text-xl font-semibold">Reports</h1><p className="mt-1 text-sm text-muted-foreground">Closed-transaction activity for the selected reporting window.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Closings" value={summary.closings} change={summary.deltaPct.closings} /><Metric label="Closed volume" value={money(summary.volume)} change={summary.deltaPct.volume} /><Metric label="Commission recorded" value={money(summary.commission)} change={summary.deltaPct.commission} /><Metric label="Missing financial data" value={summary.missingDataCount} /></div><Card><CardHeader><CardTitle>Closing trend</CardTitle></CardHeader><CardContent>{trend.length ? <div className="flex h-48 items-end gap-2 border-b border-l p-3" aria-label="Closing trend chart">{trend.map((point) => <div key={point.bucket} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-1" title={`${point.closings} closings`}><span className="text-xs">{point.closings}</span><div className="w-full max-w-10 rounded-t bg-primary" style={{ height: `${Math.max(8, point.closings / max * 130)}px` }} /><span className="truncate text-[10px] text-muted-foreground">{new Date(point.bucket).toLocaleDateString(undefined, { month: "short" })}</span></div>)}</div> : <Empty compact title="No trend data" description="There are no closed transactions in this reporting window." />}</CardContent></Card><Card><CardHeader><CardTitle>Forecast</CardTitle><p className="text-xs text-muted-foreground">Forecast only — projected values are probability-weighted estimates, not guaranteed results.</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Metric label="Projected closings" value={forecast.projectedClosings.toFixed(1)} /><Metric label="Projected volume" value={money(forecast.projectedVolume)} /><Metric label="Projected commission" value={money(forecast.projectedCommission)} /></CardContent></Card><MarketReports /></div>;
}

function MarketReports() {
  const [data, setData] = useState<ReportsResponse | null>(null); const [propertyId, setPropertyId] = useState(""); const [title, setTitle] = useState(""); const [address, setAddress] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setError(""); setData(await request("/api/agent/market-reports?limit=20")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load market reports."); } }, []);
  useEffect(() => { void load(); }, [load]);
  const generate = async () => { try { setBusy(true); await request("/api/agent/market-reports/generate", { method: "POST", body: JSON.stringify({ propertyId }) }); setPropertyId(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to generate report."); } finally { setBusy(false); } };
  const create = async () => { try { setBusy(true); await request("/api/agent/market-reports", { method: "POST", body: JSON.stringify({ title, subjectPropertyAddress: address }) }); setTitle(""); setAddress(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create report."); } finally { setBusy(false); } };
  const save = async () => { if (!editing) return; try { setBusy(true); await request(`/api/agent/market-reports/${editing}`, { method: "PUT", body: JSON.stringify({ title, subjectPropertyAddress: address }) }); setEditing(null); setTitle(""); setAddress(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update report."); } finally { setBusy(false); } };
  const remove = async (id: string) => { if (!window.confirm("Delete this market report?")) return; await request(`/api/agent/market-reports/${id}`, { method: "DELETE" }); await load(); };
  if (!data) return <Skeleton aria-label="Loading market reports" className="h-48 w-full" />;
  return <Card><CardHeader><CardTitle>Market reports</CardTitle><p className="text-sm text-muted-foreground">Create or generate a report for a property. Generated reports may contain AI-assisted analysis; review before sharing.</p></CardHeader><CardContent className="space-y-4">{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}<div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input aria-label="Property ID for report generation" placeholder="Property ID" value={propertyId} onChange={(e) => setPropertyId(e.target.value)} /><Button disabled={!propertyId.trim() || busy} onClick={() => void generate()}>Generate report</Button></div><div className="grid gap-2 sm:grid-cols-2"><Input aria-label="Market report title" placeholder="Report title" value={title} onChange={(e) => setTitle(e.target.value)} /><Input aria-label="Subject property address" placeholder="Subject property address" value={address} onChange={(e) => setAddress(e.target.value)} /><Button className="sm:col-span-2" variant="outline" disabled={!title.trim() || !address.trim() || busy} onClick={() => void (editing ? save() : create())}>{editing ? "Save report" : "Create report"}</Button>{editing ? <Button className="sm:col-span-2" variant="ghost" onClick={() => { setEditing(null); setTitle(""); setAddress(""); }}>Cancel edit</Button> : null}</div>{data.reports.length ? <div className="divide-y rounded-md border">{data.reports.map((report) => <div key={report.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><Link className="font-medium hover:underline" href={`/agent/market-reports/${report.id}`}>{report.title}</Link><p className="text-xs text-muted-foreground">{report.subjectPropertyAddress} · {report.status ?? "DRAFT"}</p></div><div className="flex gap-2"><Button size="xs" variant="ghost" onClick={() => { setEditing(report.id); setTitle(report.title); setAddress(report.subjectPropertyAddress); }}>Edit</Button><Button size="xs" variant="ghost" onClick={() => void remove(report.id)}>Delete</Button></div></div>)}</div> : <Empty compact title="No market reports" description="Generate a report from a property or create one manually." />}</CardContent></Card>;
}

export function AgentMarketReportDetail({ id }: { id: string }) {
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState("");
  useEffect(() => { void request(`/api/agent/market-reports/${id}`).then(setReport).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load report.")); }, [id]);
  if (error) return <ErrorState message={error} retry={() => window.location.reload()} />; if (!report) return <Skeleton aria-label="Loading market report" className="h-96 w-full" />;
  return <article className="flex flex-col gap-6 print:text-black"><div><Link href="/agent/reports" className="text-sm text-primary hover:underline">Back to reports</Link><h1 className="mt-2 text-2xl font-semibold">{report.title}</h1><p className="text-sm text-muted-foreground">{report.subjectPropertyAddress} · {report.status ?? "DRAFT"}</p></div><Button className="w-fit print:hidden" variant="outline" onClick={() => window.print()}>Print report</Button><Card><CardHeader><CardTitle>Subject property</CardTitle></CardHeader><CardContent><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(report.subjectPropertyData ?? {}, null, 2)}</pre></CardContent></Card><Card><CardHeader><CardTitle>Comparable properties</CardTitle></CardHeader><CardContent>{report.comparables?.length ? <pre className="whitespace-pre-wrap text-sm">{JSON.stringify(report.comparables, null, 2)}</pre> : <Empty compact title="No comparable properties" description="This report contains no comparable property data." />}</CardContent></Card>{report.aiAnalysis ? <Card><CardHeader><CardTitle>Analysis</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm">{report.aiAnalysis}</p><p className="mt-3 text-xs text-muted-foreground">Review this analysis and all underlying data before relying on it or sharing it.</p></CardContent></Card> : null}</article>;
}
