"use client";
import { useState } from 'react';
import { Button } from '@realestategear/ui/button';
import { Input } from '@realestategear/ui/input';
import { Label } from '@realestategear/ui/label';

type Area = { id: string; slug: string; name: string; isPublished: boolean; position: number };
type Collection = Area & { predicate: unknown };
type Coverage = { availableAreas: Array<{ slug: string; name: string }>; availableTags: Array<{ slug: string; label: string }> };
async function call(path: string, init?: RequestInit) { const response = await fetch(`/api/proxy/owner${path}`, { ...init, headers: { 'content-type': 'application/json', ...init?.headers } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error ?? 'Request failed'); return response.status === 204 ? null : response.json(); }

export function OwnerAreasManager({ initial, coverage }: { initial: Area[]; coverage: Coverage }) {
  const [items, setItems] = useState(initial); const [error, setError] = useState('');
  async function add(configSlug: string) { try { const item = await call('/areas', { method: 'POST', body: JSON.stringify({ configSlug }) }); setItems((old) => [...old, item]); } catch (e) { setError(String(e)); } }
  async function patch(item: Area, data: object) { const updated = await call(`/areas/${item.id}`, { method: 'PATCH', body: JSON.stringify(data) }); setItems((old) => old.map((v) => v.id === item.id ? updated : v)); }
  return <Panel title="Geographic areas" note="Areas come from deployment configuration. Advanced geometry cannot be edited here."><div className="flex flex-wrap gap-2">{coverage.availableAreas.filter((a) => !items.some((i) => i.slug === a.slug)).map((area) => <Button key={area.slug} variant="outline" onClick={() => add(area.slug)}>Add {area.name}</Button>)}</div>{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="grid gap-3">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border border-border bg-card p-4"><div><h2 className="font-bold">{item.name}</h2><p className="text-xs text-muted-foreground">/{item.slug}</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => patch(item, { position: Math.max(0, item.position - 1) })}>Move up</Button><Button onClick={() => patch(item, { isPublished: !item.isPublished })}>{item.isPublished ? 'Unpublish' : 'Publish'}</Button></div></div>)}</div></Panel>;
}

export function OwnerCollectionsManager({ portalId, initial, coverage }: { portalId: string; initial: Collection[]; coverage: Coverage }) {
  const [items, setItems] = useState(initial); const [preview, setPreview] = useState<{ count: number; examples: Array<{ id: string; address: string; whyMatched: string }> } | null>(null); const [error, setError] = useState('');
  async function create(form: FormData) { try { const tagsAny = coverage.availableTags.filter((t) => form.get(`tag:${t.slug}`)).map((t) => t.slug); const areaSlugs = coverage.availableAreas.filter((a) => form.get(`area:${a.slug}`)).map((a) => a.slug); const minPrice = Number(form.get('minPrice')) || undefined; const beds = Number(form.get('beds')) || undefined; const propertyTypes = form.get('propertyType') ? [String(form.get('propertyType'))] : undefined; const predicate = { ...(tagsAny.length ? { tagsAny } : {}), ...(areaSlugs.length ? { areaSlugs } : {}), ...(propertyTypes ? { propertyTypes } : {}), ...(minPrice ? { price: { min: minPrice, nulls: 'exclude' } } : {}), ...(beds ? { beds: { min: beds, nulls: 'exclude' } } : {}) }; const item = await call('/collections', { method: 'POST', body: JSON.stringify({ portalId, name: form.get('name'), slug: form.get('slug'), predicate }) }); setItems((old) => [...old, item]); } catch (e) { setError(String(e)); } }
  async function patch(item: Collection, data: object) { const updated = await call(`/collections/${item.id}`, { method: 'PATCH', body: JSON.stringify(data) }); setItems((old) => old.map((v) => v.id === item.id ? updated : v)); }
  async function override(item: Collection, form: FormData) { try { await call(`/collections/${item.id}/overrides/${form.get('propertyId')}`, { method: 'PUT', body: JSON.stringify({ decision: form.get('decision') }) }); } catch (e) { setError(String(e)); } }
  return <Panel title="Listing collections" note="EXCLUDE always wins. INCLUDE bypasses collection filters, but never IDX, status, board, approval, or suspension gates."><form action={create} className="grid gap-3 rounded-md border border-border bg-card p-4 sm:grid-cols-2"><Field name="name" label="Name" /><Field name="slug" label="Stable slug" /><Field name="minPrice" label="Minimum price" type="number" /><Field name="beds" label="Minimum beds" type="number" /><label className="text-sm font-semibold">Property type<select name="propertyType" className="mt-1 block h-9 w-full border border-border bg-background px-2"><option value="">Any</option><option value="SINGLE_FAMILY">Single family</option><option value="CONDO">Condo</option><option value="TOWNHOUSE">Townhouse</option><option value="LAND">Land</option></select></label><div><p className="text-sm font-semibold">Areas</p>{coverage.availableAreas.map((a) => <label key={a.slug} className="mr-3 text-sm"><input type="checkbox" name={`area:${a.slug}`} /> {a.name}</label>)}</div><div className="sm:col-span-2"><p className="text-sm font-semibold">Tags (match any)</p>{coverage.availableTags.map((t) => <label key={t.slug} className="mr-3 text-sm"><input type="checkbox" name={`tag:${t.slug}`} /> {t.label}</label>)}</div><Button type="submit">Create collection</Button></form>{error ? <p className="text-sm text-destructive">{error}</p> : null}<div className="grid gap-3">{items.map((item) => <div key={item.id} className="rounded-md border border-border bg-card p-4"><div className="flex items-start justify-between"><div><h2 className="font-bold">{item.name}</h2><p className="text-xs text-muted-foreground">/{item.slug}</p></div><div className="flex gap-2"><Button variant="outline" onClick={async () => setPreview(await call(`/collections/${item.id}/preview`, { method: 'POST', body: '{}' }))}>Preview</Button><Button onClick={() => patch(item, { isPublished: !item.isPublished })}>{item.isPublished ? 'Unpublish' : 'Publish'}</Button></div></div><form action={(data) => override(item, data)} className="mt-4 flex gap-2"><Input name="propertyId" placeholder="Property ID" required /><select name="decision" className="border border-border bg-background px-2"><option value="INCLUDE">Include</option><option value="EXCLUDE">Exclude</option></select><Button variant="outline">Apply override</Button></form></div>)}</div>{preview ? <div className="rounded-md border border-border bg-card p-4"><h2 className="font-bold">{preview.count.toLocaleString()} matches</h2>{preview.examples.map((e) => <p key={e.id} className="mt-2 text-sm"><strong>{e.address}</strong>: {e.whyMatched}</p>)}</div> : null}</Panel>;
}
function Field({ name, label, type = 'text' }: { name: string; label: string; type?: string }) { return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} required={name === 'name' || name === 'slug'} /></div>; }
function Panel({ title, note, children }: { title: string; note: string; children: React.ReactNode }) { return <div className="mx-auto grid max-w-5xl gap-5 px-4 py-10 sm:px-6"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{note}</p></div>{children}</div>; }
